---
title: "Assignment_Codebook"
author: "Ben Siegelman"
date: "2023-09-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Summary

This codebook describes a modified dataset taken from the UAC HAR Dataset. In short, the raw data was extracted from a .zip file, tidied, mean and standard deviation values calculated, activity codes substituted for descriptive text, and variable names turned into descriptive text. A second dataset was also produced, showing the average values for each subject and activity pairing. More details below, followed by the original README and features_info text from the raw data.

==================================================================

## Data Manipulation Description

The 'final_data' table is a tidied dataset that modifies aspects of the UCI HAR Dataset raw data.

- The 'training' and 'test' datasets were merged to create a single dataset

- The modified dataset diplays the Mean and Standard Deviation values for each measurement

- Activity codes are replaced with Activity Names

- Column Names were modified to be more descriptive

In addition, a second dataset 'activity_subj_averages' was created. This dataset displays the mean values for each unique activity/subject pairing.

==================================================================

## Units

Accleration is represented in standard gravity units 'g'.

Gyroscope readings are represented in radians/second

==================================================================

## Variables

Please refer to the [Variable List](variable_list.md) for a comprehensive list of all variables in the dataset.

For explanations of these variables, please see the "Features Selection" and README explanations from the original raw data below. In addition, below is a 'Legend' that will help explain variables:

"Mean": At the start of a variable name, indicates the mean calculation across each measurement

"SD": At the start of a variable name, indicates the Standard Deviation calculation across each measurement

"Time Domain": Time Domain signals captured at a constant rate of 50 Hz, then filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise

"Frequency Domain": Frequency Domain signals produced by applying a Fast Fourier Transform (FFT)

"Body Acceleration" and "Gravity Acceleration": Accelerometer readings separated out from each other using a low pass Butterworth filter with a corner frequency of 0.3 Hz. Body acceleration is calculated by subtracting Gravity from Total

"Gyroscope": Gyroscope 3-axial raw signal readings

"X/Y/Z Axis": Denotes the axis of the gyroscope readings

"Angle": angle between two vectors

"Jerk": Jerk signals derived from body linear acceleration and angular velocity, across each axis.

"Magnitude": Magnitude of three-dimensional Jerk signals calculated using the Euclidean norm.

"Total": Indicates Total Acceleration readings

"mean": Mean value
"std": Standard deviation
"mad": Median absolute deviation 
"max": Largest value in array
"min": Smallest value in array
"sma"): Signal magnitude area
"energy": Energy measure. Sum of the squares divided by the number of values. 
"iqr": Interquartile range 
"entropy": Signal entropy
"arCoeff": Autorregresion coefficients with Burg order equal to 4.
"correlation": correlation coefficient between two signals
"maxInds": index of the frequency component with largest magnitude.
"meanFreq": Weighted average of the frequency components to obtain a mean frequency.
"skewness": skewness of the frequency domain signal 
"kurtosis": kurtosis of the frequency domain signal 
"Bands Energy": Energy of a frequency interval within the 64 bins of the FFT of each window.


==================================================================

